# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maltrato', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('herido', models.CharField(max_length=2)),
            ],
        ),
    ]
