# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeyCholito', '0003_remove_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
