# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeyCholito', '0004_remove_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
