# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeyCholito', '0006_auto_20171010_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='comentario',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
